from django.conf.urls.defaults  import *
from django.utils.translation   import ugettext_lazy as trans

urlpatterns= patterns('documento.views',
                        url('^documentos/$', 'documentos',
                            {'vTitulo': trans(u'documentos')}, name='documentos'), 
                        url('^checkin/(?P<vIDVersao>\d+)/$', 'checkin',
                            {'vTitulo': trans(u'checkin')}, name='checkin'),
                        url('^checkout/(?P<vIDVersao>\d+)/$', 'checkout',
                            {'vTitulo': trans(u'checkout')}, name='checkout'),
                        url('^aprovar_documento/(?P<vIDVersao>\d+)/$', 'aprovar',
                            {'vTitulo': trans(u'aprovar')}, name='aprovar'),
                        url('^reprovar_documento/(?P<vIDVersao>\d+)/$', 'reprovar',
                            {'vTitulo': trans(u'reprovar')}, name='reprovar'),
                        url('^excluir_documento/(?P<vIDVersao>\d+)/$', 'excluir',
                            {'vTitulo': trans(u'excluir')}, name='excluir'),
                        url('^cria_arvore/$', 'criaArvore',
                            {'vTitulo': trans(u'criaArvore')}, name='criaArvore'),
                        url('^download/(?P<vIDVersao>\d+)/$', 'download',
                            {'vTitulo': trans(u'download')}, name='download'),
                        url('^visualizar/(?P<vIDVersao>\d+)/$', 'visualizar',
                            {'vTitulo': trans(u'visualizar')}, name='visualizar'),
                        url('^importar/$', 'importar',
                            {'vTitulo': trans(u'importar')}, name='importar'),
                        url('^tabela_documentos/$', 'tabelaDocumentos',
                            {'vTitulo': trans(u'tabelaDocumentos')}, name='tabelaDocumentos'),
                        url('^versoes_selecionadas/(?P<vListaIDVersoes>[-\w]+)/$', 'versoesSelecionadas',
                            {'vTitulo': trans(u'versoesSelecionadas')}, name='versoesSelecionadas'),
                        url('^pasta_raiz/$', 'obtemPastaRaiz',
                            {'vTitulo': trans(u'obtemPastaRaiz')}, name='obtemPastaRaiz'),
                        url('^digitalizar/$', 'digitalizar', name='digitalizar'),
                      )